package jamesstocktonj1:wasi-lib;

world wasi-lib {
    // keyvalue
    import wasi:keyvalue/store@0.2.0-draft;
    import wasi:keyvalue/atomics@0.2.0-draft;

    // config
    import wasi:config/runtime@0.2.0-draft;
}